### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by cspayne**
- missing lang tags added
- Linked Data Platforms: incorrect void:classPartition and void:class triples removed, "Open Refine" label corrected to "OpenRefine"
- spelling/capitalization mistakes corrected
- dcterms changed to preferred prefix dct

### CODE REVIEW

**Review by briesenberg07 — APPROVED** [review]
I approve all changes 👍🏻  

I understand all changes except why the change in [this commit](https://github.com/uwlib-cams/uwlswd_vocabs/pull/33/commits/91b4a22d1e1ddb419c71c37deb5d2354508c0977) -- per @gerontakos ' [comment](https://github.com/uwlib-cams/uwlswd/issues/41#issuecomment-1694015449)...

>  the bnode in this dataset is flat-out wrong

...and [vocabs \#20](https://github.com/uwlib-cams/uwlswd_vocabs/issues/20) had to be made (don't understand why the void:classPartition with bnode value is incorrect).

But I'm not aware of any harm that making the change will cause, so I don't think there's any reason not to merge.

**Comment by briesenberg07** [comment]
@cspayne 
@gerontakos 
uwlswd_vocabs branch `cleanup` merged to main

**Comment by briesenberg07** [comment]
@cspayne I think you mentioned some DataCite XML changes still need to be made, is this correct?  
I understood this to mean improvement of some metadata for the resources here, but *no changed URLs*

**Comment by cspayne** [comment]
> @cspayne I think you mentioned some DataCite XML changes still need to be made, is this correct? I understood this to mean improvement of some metadata for the resources here, but _no changed URLs_

Yes! Now that it is merged I will update those files both in DataCite and in the UWLSWD repo.

**Pull request merged**
